# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Tue Aug  5 17:58:28 2008
#      by: PyQt4 UI code generator 4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(QtCore.QSize(QtCore.QRect(0,0,734,411).size()).expandedTo(MainWindow.minimumSizeHint()))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(734,411))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setSpacing(-1)
        self.vboxlayout.setObjectName("vboxlayout")
        self.Tabber = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabber.sizePolicy().hasHeightForWidth())
        self.Tabber.setSizePolicy(sizePolicy)
        self.Tabber.setObjectName("Tabber")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridlayout = QtGui.QGridLayout(self.tab)
        self.gridlayout.setObjectName("gridlayout")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName("gridlayout1")
        self.Str = QtGui.QSpinBox(self.tab)
        self.Str.setMaximumSize(QtCore.QSize(60,60))
        self.Str.setMinimum(-9)
        self.Str.setMaximum(10)
        self.Str.setProperty("value",QtCore.QVariant(0))
        self.Str.setObjectName("Str")
        self.gridlayout1.addWidget(self.Str,0,1,1,1)
        self.Cha = QtGui.QSpinBox(self.tab)
        self.Cha.setMaximumSize(QtCore.QSize(60,60))
        self.Cha.setMinimum(-9)
        self.Cha.setMaximum(10)
        self.Cha.setProperty("value",QtCore.QVariant(0))
        self.Cha.setObjectName("Cha")
        self.gridlayout1.addWidget(self.Cha,5,1,1,1)
        self.Dex = QtGui.QSpinBox(self.tab)
        self.Dex.setMaximumSize(QtCore.QSize(60,60))
        self.Dex.setMinimum(-9)
        self.Dex.setMaximum(10)
        self.Dex.setProperty("value",QtCore.QVariant(0))
        self.Dex.setObjectName("Dex")
        self.gridlayout1.addWidget(self.Dex,1,1,1,1)
        self.Wil = QtGui.QSpinBox(self.tab)
        self.Wil.setMaximumSize(QtCore.QSize(60,60))
        self.Wil.setMinimum(-9)
        self.Wil.setMaximum(10)
        self.Wil.setProperty("value",QtCore.QVariant(0))
        self.Wil.setObjectName("Wil")
        self.gridlayout1.addWidget(self.Wil,4,1,1,1)
        self.Int = QtGui.QSpinBox(self.tab)
        self.Int.setMaximumSize(QtCore.QSize(60,60))
        self.Int.setMinimum(-9)
        self.Int.setMaximum(10)
        self.Int.setProperty("value",QtCore.QVariant(0))
        self.Int.setObjectName("Int")
        self.gridlayout1.addWidget(self.Int,3,1,1,1)
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridlayout1.addWidget(self.label_7,0,0,1,1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridlayout1.addWidget(self.label_8,1,0,1,1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridlayout1.addWidget(self.label_9,2,0,1,1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridlayout1.addWidget(self.label_10,3,0,1,1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridlayout1.addWidget(self.label_11,4,0,1,1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridlayout1.addWidget(self.label_12,5,0,1,1)
        self.Con = QtGui.QSpinBox(self.tab)
        self.Con.setMaximumSize(QtCore.QSize(60,60))
        self.Con.setMinimum(-9)
        self.Con.setMaximum(10)
        self.Con.setProperty("value",QtCore.QVariant(0))
        self.Con.setObjectName("Con")
        self.gridlayout1.addWidget(self.Con,2,1,1,1)
        self.hboxlayout1.addLayout(self.gridlayout1)
        spacerItem = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setObjectName("gridlayout2")
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.gridlayout2.addWidget(self.label_13,0,0,1,1)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.gridlayout2.addWidget(self.label_14,1,0,1,1)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.gridlayout2.addWidget(self.label_15,2,0,1,1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.gridlayout2.addWidget(self.label_16,3,0,1,1)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.gridlayout2.addWidget(self.label_17,4,0,1,1)
        self.D = QtGui.QLineEdit(self.tab)
        self.D.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D.sizePolicy().hasHeightForWidth())
        self.D.setSizePolicy(sizePolicy)
        self.D.setMaximumSize(QtCore.QSize(50,16777215))
        self.D.setAlignment(QtCore.Qt.AlignCenter)
        self.D.setReadOnly(True)
        self.D.setObjectName("D")
        self.gridlayout2.addWidget(self.D,2,1,1,1)
        self.A = QtGui.QLineEdit(self.tab)
        self.A.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A.sizePolicy().hasHeightForWidth())
        self.A.setSizePolicy(sizePolicy)
        self.A.setMaximumSize(QtCore.QSize(50,16777215))
        self.A.setAlignment(QtCore.Qt.AlignCenter)
        self.A.setReadOnly(True)
        self.A.setObjectName("A")
        self.gridlayout2.addWidget(self.A,0,1,1,1)
        self.M = QtGui.QLineEdit(self.tab)
        self.M.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M.sizePolicy().hasHeightForWidth())
        self.M.setSizePolicy(sizePolicy)
        self.M.setMaximumSize(QtCore.QSize(50,16777215))
        self.M.setAlignment(QtCore.Qt.AlignCenter)
        self.M.setReadOnly(True)
        self.M.setObjectName("M")
        self.gridlayout2.addWidget(self.M,1,1,1,1)
        self.P = QtGui.QLineEdit(self.tab)
        self.P.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.P.sizePolicy().hasHeightForWidth())
        self.P.setSizePolicy(sizePolicy)
        self.P.setMaximumSize(QtCore.QSize(50,16777215))
        self.P.setAlignment(QtCore.Qt.AlignCenter)
        self.P.setReadOnly(True)
        self.P.setObjectName("P")
        self.gridlayout2.addWidget(self.P,3,1,1,1)
        self.R = QtGui.QLineEdit(self.tab)
        self.R.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R.sizePolicy().hasHeightForWidth())
        self.R.setSizePolicy(sizePolicy)
        self.R.setMaximumSize(QtCore.QSize(50,16777215))
        self.R.setAlignment(QtCore.Qt.AlignCenter)
        self.R.setReadOnly(True)
        self.R.setObjectName("R")
        self.gridlayout2.addWidget(self.R,4,1,1,1)
        self.hboxlayout1.addLayout(self.gridlayout2)
        spacerItem1 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.gridlayout3 = QtGui.QGridLayout()
        self.gridlayout3.setObjectName("gridlayout3")
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setObjectName("label_18")
        self.gridlayout3.addWidget(self.label_18,0,0,1,1)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setObjectName("label_19")
        self.gridlayout3.addWidget(self.label_19,1,0,1,1)
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.gridlayout3.addWidget(self.label_20,2,0,1,1)
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setObjectName("label_21")
        self.gridlayout3.addWidget(self.label_21,3,0,1,1)
        self.I = QtGui.QLineEdit(self.tab)
        self.I.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.I.sizePolicy().hasHeightForWidth())
        self.I.setSizePolicy(sizePolicy)
        self.I.setMaximumSize(QtCore.QSize(50,16777215))
        self.I.setAlignment(QtCore.Qt.AlignCenter)
        self.I.setReadOnly(True)
        self.I.setObjectName("I")
        self.gridlayout3.addWidget(self.I,2,1,1,1)
        self.HP = QtGui.QLineEdit(self.tab)
        self.HP.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HP.sizePolicy().hasHeightForWidth())
        self.HP.setSizePolicy(sizePolicy)
        self.HP.setMaximumSize(QtCore.QSize(50,16777215))
        self.HP.setAlignment(QtCore.Qt.AlignCenter)
        self.HP.setObjectName("HP")
        self.gridlayout3.addWidget(self.HP,0,1,1,1)
        self.MP = QtGui.QLineEdit(self.tab)
        self.MP.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MP.sizePolicy().hasHeightForWidth())
        self.MP.setSizePolicy(sizePolicy)
        self.MP.setMaximumSize(QtCore.QSize(50,16777215))
        self.MP.setAlignment(QtCore.Qt.AlignCenter)
        self.MP.setReadOnly(True)
        self.MP.setObjectName("MP")
        self.gridlayout3.addWidget(self.MP,1,1,1,1)
        self.HC = QtGui.QLineEdit(self.tab)
        self.HC.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HC.sizePolicy().hasHeightForWidth())
        self.HC.setSizePolicy(sizePolicy)
        self.HC.setMaximumSize(QtCore.QSize(50,16777215))
        self.HC.setAlignment(QtCore.Qt.AlignCenter)
        self.HC.setReadOnly(True)
        self.HC.setObjectName("HC")
        self.gridlayout3.addWidget(self.HC,3,1,1,1)
        self.hboxlayout1.addLayout(self.gridlayout3)
        self.gridlayout.addLayout(self.hboxlayout1,3,0,1,1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setMargin(5)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.rand_2K6_4 = QtGui.QPushButton(self.tab)
        self.rand_2K6_4.setObjectName("rand_2K6_4")
        self.hboxlayout2.addWidget(self.rand_2K6_4)
        self.rand_2K6_6 = QtGui.QPushButton(self.tab)
        self.rand_2K6_6.setObjectName("rand_2K6_6")
        self.hboxlayout2.addWidget(self.rand_2K6_6)
        self.rand_KV = QtGui.QPushButton(self.tab)
        self.rand_KV.setObjectName("rand_KV")
        self.hboxlayout2.addWidget(self.rand_KV)
        self.gridlayout.addLayout(self.hboxlayout2,6,0,1,1)
        spacerItem2 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem2,5,0,1,1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setObjectName("label_22")
        self.hboxlayout3.addWidget(self.label_22)
        self.Name = QtGui.QLineEdit(self.tab)
        self.Name.setObjectName("Name")
        self.hboxlayout3.addWidget(self.Name)
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setObjectName("label_23")
        self.hboxlayout3.addWidget(self.label_23)
        self.Race = QtGui.QLineEdit(self.tab)
        self.Race.setObjectName("Race")
        self.hboxlayout3.addWidget(self.Race)
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setObjectName("label_24")
        self.hboxlayout3.addWidget(self.label_24)
        self.Comment = QtGui.QLineEdit(self.tab)
        self.Comment.setObjectName("Comment")
        self.hboxlayout3.addWidget(self.Comment)
        self.gridlayout.addLayout(self.hboxlayout3,0,0,1,1)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridlayout.addWidget(self.line,1,0,1,1)
        spacerItem3 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout.addItem(spacerItem3,4,0,1,1)
        self.Tabber.addTab(self.tab,"")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridlayout4 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout4.setObjectName("gridlayout4")
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.SkillList = QtGui.QListWidget(self.tab_2)
        self.SkillList.setSelectionRectVisible(True)
        self.SkillList.setSortingEnabled(True)
        self.SkillList.setObjectName("SkillList")
        self.hboxlayout4.addWidget(self.SkillList)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.SkillAdd = QtGui.QPushButton(self.tab_2)
        self.SkillAdd.setObjectName("SkillAdd")
        self.vboxlayout1.addWidget(self.SkillAdd)
        spacerItem4 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem4)
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setObjectName("label")
        self.vboxlayout1.addWidget(self.label)
        self.SkillMod = QtGui.QSpinBox(self.tab_2)
        self.SkillMod.setMinimum(-9)
        self.SkillMod.setMaximum(10)
        self.SkillMod.setObjectName("SkillMod")
        self.vboxlayout1.addWidget(self.SkillMod)
        spacerItem5 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem5)
        self.SkillDel = QtGui.QPushButton(self.tab_2)
        self.SkillDel.setObjectName("SkillDel")
        self.vboxlayout1.addWidget(self.SkillDel)
        self.hboxlayout4.addLayout(self.vboxlayout1)
        self.SkillAdded = QtGui.QListWidget(self.tab_2)
        self.SkillAdded.setSortingEnabled(True)
        self.SkillAdded.setObjectName("SkillAdded")
        self.hboxlayout4.addWidget(self.SkillAdded)
        self.gridlayout4.addLayout(self.hboxlayout4,0,0,1,1)
        self.Tabber.addTab(self.tab_2,"")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.tab_3)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.WeaponList = QtGui.QListWidget(self.tab_3)
        self.WeaponList.setObjectName("WeaponList")
        self.hboxlayout5.addWidget(self.WeaponList)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.WeaponAdd = QtGui.QPushButton(self.tab_3)
        self.WeaponAdd.setObjectName("WeaponAdd")
        self.vboxlayout3.addWidget(self.WeaponAdd)
        self.WeaponDel = QtGui.QPushButton(self.tab_3)
        self.WeaponDel.setObjectName("WeaponDel")
        self.vboxlayout3.addWidget(self.WeaponDel)
        self.hboxlayout5.addLayout(self.vboxlayout3)
        self.WeaponAdded = QtGui.QListWidget(self.tab_3)
        self.WeaponAdded.setObjectName("WeaponAdded")
        self.hboxlayout5.addWidget(self.WeaponAdded)
        self.vboxlayout2.addLayout(self.hboxlayout5)
        self.line_2 = QtGui.QFrame(self.tab_3)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.vboxlayout2.addWidget(self.line_2)
        self.line_3 = QtGui.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.vboxlayout2.addWidget(self.line_3)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.ArmorList = QtGui.QListWidget(self.tab_3)
        self.ArmorList.setObjectName("ArmorList")
        self.hboxlayout6.addWidget(self.ArmorList)
        self.vboxlayout4 = QtGui.QVBoxLayout()
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.ArmorAdd = QtGui.QPushButton(self.tab_3)
        self.ArmorAdd.setObjectName("ArmorAdd")
        self.vboxlayout4.addWidget(self.ArmorAdd)
        self.ArmorDel = QtGui.QPushButton(self.tab_3)
        self.ArmorDel.setObjectName("ArmorDel")
        self.vboxlayout4.addWidget(self.ArmorDel)
        self.hboxlayout6.addLayout(self.vboxlayout4)
        self.ArmorAdded = QtGui.QListWidget(self.tab_3)
        self.ArmorAdded.setObjectName("ArmorAdded")
        self.hboxlayout6.addWidget(self.ArmorAdded)
        self.vboxlayout2.addLayout(self.hboxlayout6)
        self.Tabber.addTab(self.tab_3,"")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridlayout5 = QtGui.QGridLayout(self.tab_4)
        self.gridlayout5.setObjectName("gridlayout5")
        self.ExportText = QtGui.QTextEdit(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Fixed [Misc]")
        self.ExportText.setFont(font)
        self.ExportText.setObjectName("ExportText")
        self.gridlayout5.addWidget(self.ExportText,0,0,1,1)
        self.Tabber.addTab(self.tab_4,"")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridlayout6 = QtGui.QGridLayout(self.tab_5)
        self.gridlayout6.setObjectName("gridlayout6")
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.NewSkillList = QtGui.QListWidget(self.tab_5)
        self.NewSkillList.setSortingEnabled(True)
        self.NewSkillList.setObjectName("NewSkillList")
        self.hboxlayout7.addWidget(self.NewSkillList)
        self.vboxlayout5 = QtGui.QVBoxLayout()
        self.vboxlayout5.setObjectName("vboxlayout5")
        spacerItem6 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout5.addItem(spacerItem6)
        self.NewSkillAdd = QtGui.QPushButton(self.tab_5)
        self.NewSkillAdd.setObjectName("NewSkillAdd")
        self.vboxlayout5.addWidget(self.NewSkillAdd)
        self.NewSkillDel = QtGui.QPushButton(self.tab_5)
        self.NewSkillDel.setObjectName("NewSkillDel")
        self.vboxlayout5.addWidget(self.NewSkillDel)
        spacerItem7 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout5.addItem(spacerItem7)
        self.hboxlayout7.addLayout(self.vboxlayout5)
        self.vboxlayout6 = QtGui.QVBoxLayout()
        self.vboxlayout6.setObjectName("vboxlayout6")
        self.label_2 = QtGui.QLabel(self.tab_5)
        self.label_2.setObjectName("label_2")
        self.vboxlayout6.addWidget(self.label_2)
        self.NewSkillName = QtGui.QLineEdit(self.tab_5)
        self.NewSkillName.setObjectName("NewSkillName")
        self.vboxlayout6.addWidget(self.NewSkillName)
        self.label_3 = QtGui.QLabel(self.tab_5)
        self.label_3.setObjectName("label_3")
        self.vboxlayout6.addWidget(self.label_3)
        self.NewSkillAbility = QtGui.QComboBox(self.tab_5)
        self.NewSkillAbility.setObjectName("NewSkillAbility")
        self.vboxlayout6.addWidget(self.NewSkillAbility)
        self.NewSkillCond = QtGui.QCheckBox(self.tab_5)
        self.NewSkillCond.setObjectName("NewSkillCond")
        self.vboxlayout6.addWidget(self.NewSkillCond)
        spacerItem8 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout6.addItem(spacerItem8)
        self.hboxlayout7.addLayout(self.vboxlayout6)
        self.gridlayout6.addLayout(self.hboxlayout7,0,1,1,1)
        self.Tabber.addTab(self.tab_5,"")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridlayout7 = QtGui.QGridLayout(self.tab_6)
        self.gridlayout7.setObjectName("gridlayout7")
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.NewWeaponList = QtGui.QListWidget(self.tab_6)
        self.NewWeaponList.setSelectionRectVisible(True)
        self.NewWeaponList.setSortingEnabled(True)
        self.NewWeaponList.setObjectName("NewWeaponList")
        self.hboxlayout8.addWidget(self.NewWeaponList)
        self.vboxlayout7 = QtGui.QVBoxLayout()
        self.vboxlayout7.setObjectName("vboxlayout7")
        self.NewWeaponAdd = QtGui.QPushButton(self.tab_6)
        self.NewWeaponAdd.setObjectName("NewWeaponAdd")
        self.vboxlayout7.addWidget(self.NewWeaponAdd)
        self.NewWeaponDel = QtGui.QPushButton(self.tab_6)
        self.NewWeaponDel.setObjectName("NewWeaponDel")
        self.vboxlayout7.addWidget(self.NewWeaponDel)
        self.hboxlayout8.addLayout(self.vboxlayout7)
        self.vboxlayout8 = QtGui.QVBoxLayout()
        self.vboxlayout8.setObjectName("vboxlayout8")
        self.label_6 = QtGui.QLabel(self.tab_6)
        self.label_6.setObjectName("label_6")
        self.vboxlayout8.addWidget(self.label_6)
        self.NewWeaponName = QtGui.QLineEdit(self.tab_6)
        self.NewWeaponName.setObjectName("NewWeaponName")
        self.vboxlayout8.addWidget(self.NewWeaponName)
        self.gridlayout8 = QtGui.QGridLayout()
        self.gridlayout8.setObjectName("gridlayout8")
        self.NewWeaponHit = QtGui.QSpinBox(self.tab_6)
        self.NewWeaponHit.setMinimum(-9)
        self.NewWeaponHit.setMaximum(10)
        self.NewWeaponHit.setObjectName("NewWeaponHit")
        self.gridlayout8.addWidget(self.NewWeaponHit,1,0,1,1)
        self.NewWeaponDamage = QtGui.QSpinBox(self.tab_6)
        self.NewWeaponDamage.setMinimum(-9)
        self.NewWeaponDamage.setMaximum(10)
        self.NewWeaponDamage.setObjectName("NewWeaponDamage")
        self.gridlayout8.addWidget(self.NewWeaponDamage,1,1,1,1)
        self.label_5 = QtGui.QLabel(self.tab_6)
        self.label_5.setObjectName("label_5")
        self.gridlayout8.addWidget(self.label_5,0,0,1,1)
        self.label_4 = QtGui.QLabel(self.tab_6)
        self.label_4.setObjectName("label_4")
        self.gridlayout8.addWidget(self.label_4,0,1,1,1)
        self.NewWeaponIsRange = QtGui.QCheckBox(self.tab_6)
        self.NewWeaponIsRange.setObjectName("NewWeaponIsRange")
        self.gridlayout8.addWidget(self.NewWeaponIsRange,2,0,1,1)
        self.label_27 = QtGui.QLabel(self.tab_6)
        self.label_27.setObjectName("label_27")
        self.gridlayout8.addWidget(self.label_27,3,0,1,1)
        self.NewWeaponRange = QtGui.QSpinBox(self.tab_6)
        self.NewWeaponRange.setEnabled(False)
        self.NewWeaponRange.setMaximum(500)
        self.NewWeaponRange.setObjectName("NewWeaponRange")
        self.gridlayout8.addWidget(self.NewWeaponRange,3,1,1,1)
        self.vboxlayout8.addLayout(self.gridlayout8)
        spacerItem9 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout8.addItem(spacerItem9)
        self.hboxlayout8.addLayout(self.vboxlayout8)
        self.vboxlayout9 = QtGui.QVBoxLayout()
        self.vboxlayout9.setObjectName("vboxlayout9")
        self.NewWeaponSkills = QtGui.QComboBox(self.tab_6)
        self.NewWeaponSkills.setObjectName("NewWeaponSkills")
        self.vboxlayout9.addWidget(self.NewWeaponSkills)
        self.NewWeaponSkillsAdded = QtGui.QListWidget(self.tab_6)
        self.NewWeaponSkillsAdded.setSelectionRectVisible(True)
        self.NewWeaponSkillsAdded.setSortingEnabled(True)
        self.NewWeaponSkillsAdded.setObjectName("NewWeaponSkillsAdded")
        self.vboxlayout9.addWidget(self.NewWeaponSkillsAdded)
        self.hboxlayout8.addLayout(self.vboxlayout9)
        self.vboxlayout10 = QtGui.QVBoxLayout()
        self.vboxlayout10.setObjectName("vboxlayout10")
        self.NewWeaponSkillAdd = QtGui.QPushButton(self.tab_6)
        self.NewWeaponSkillAdd.setObjectName("NewWeaponSkillAdd")
        self.vboxlayout10.addWidget(self.NewWeaponSkillAdd)
        self.NewWeaponSkillDel = QtGui.QPushButton(self.tab_6)
        self.NewWeaponSkillDel.setObjectName("NewWeaponSkillDel")
        self.vboxlayout10.addWidget(self.NewWeaponSkillDel)
        self.hboxlayout8.addLayout(self.vboxlayout10)
        self.gridlayout7.addLayout(self.hboxlayout8,0,0,1,1)
        self.Tabber.addTab(self.tab_6,"")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.hboxlayout9 = QtGui.QHBoxLayout(self.tab_7)
        self.hboxlayout9.setObjectName("hboxlayout9")
        spacerItem10 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout9.addItem(spacerItem10)
        self.NewArmorList = QtGui.QListWidget(self.tab_7)
        self.NewArmorList.setObjectName("NewArmorList")
        self.hboxlayout9.addWidget(self.NewArmorList)
        self.vboxlayout11 = QtGui.QVBoxLayout()
        self.vboxlayout11.setObjectName("vboxlayout11")
        self.NewArmorAdd = QtGui.QPushButton(self.tab_7)
        self.NewArmorAdd.setObjectName("NewArmorAdd")
        self.vboxlayout11.addWidget(self.NewArmorAdd)
        self.NewArmorDel = QtGui.QPushButton(self.tab_7)
        self.NewArmorDel.setObjectName("NewArmorDel")
        self.vboxlayout11.addWidget(self.NewArmorDel)
        self.hboxlayout9.addLayout(self.vboxlayout11)
        self.vboxlayout12 = QtGui.QVBoxLayout()
        self.vboxlayout12.setObjectName("vboxlayout12")
        self.label_26 = QtGui.QLabel(self.tab_7)
        self.label_26.setObjectName("label_26")
        self.vboxlayout12.addWidget(self.label_26)
        self.NewArmorName = QtGui.QLineEdit(self.tab_7)
        self.NewArmorName.setObjectName("NewArmorName")
        self.vboxlayout12.addWidget(self.NewArmorName)
        self.label_30 = QtGui.QLabel(self.tab_7)
        self.label_30.setObjectName("label_30")
        self.vboxlayout12.addWidget(self.label_30)
        self.NewArmorDefense = QtGui.QSpinBox(self.tab_7)
        self.NewArmorDefense.setMinimum(-9)
        self.NewArmorDefense.setMaximum(10)
        self.NewArmorDefense.setObjectName("NewArmorDefense")
        self.vboxlayout12.addWidget(self.NewArmorDefense)
        self.label_31 = QtGui.QLabel(self.tab_7)
        self.label_31.setObjectName("label_31")
        self.vboxlayout12.addWidget(self.label_31)
        self.NewArmorDamage = QtGui.QSpinBox(self.tab_7)
        self.NewArmorDamage.setMinimum(-9)
        self.NewArmorDamage.setMaximum(10)
        self.NewArmorDamage.setObjectName("NewArmorDamage")
        self.vboxlayout12.addWidget(self.NewArmorDamage)
        self.label_25 = QtGui.QLabel(self.tab_7)
        self.label_25.setObjectName("label_25")
        self.vboxlayout12.addWidget(self.label_25)
        self.NewArmorInitiative = QtGui.QSpinBox(self.tab_7)
        self.NewArmorInitiative.setMinimum(-20)
        self.NewArmorInitiative.setMaximum(20)
        self.NewArmorInitiative.setObjectName("NewArmorInitiative")
        self.vboxlayout12.addWidget(self.NewArmorInitiative)
        self.hboxlayout9.addLayout(self.vboxlayout12)
        spacerItem11 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout9.addItem(spacerItem11)
        self.Tabber.addTab(self.tab_7,"")
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.hboxlayout10 = QtGui.QHBoxLayout(self.tab_9)
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.ExportStateText = QtGui.QTextEdit(self.tab_9)
        self.ExportStateText.setObjectName("ExportStateText")
        self.hboxlayout10.addWidget(self.ExportStateText)
        self.Tabber.addTab(self.tab_9,"")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.hboxlayout11 = QtGui.QHBoxLayout(self.tab_8)
        self.hboxlayout11.setObjectName("hboxlayout11")
        self.textEdit = QtGui.QTextEdit(self.tab_8)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.hboxlayout11.addWidget(self.textEdit)
        self.Tabber.addTab(self.tab_8,"")
        self.vboxlayout.addWidget(self.Tabber)
        self.hboxlayout12 = QtGui.QHBoxLayout()
        self.hboxlayout12.setSpacing(-1)
        self.hboxlayout12.setMargin(5)
        self.hboxlayout12.setObjectName("hboxlayout12")
        self.LoadCharacter = QtGui.QPushButton(self.centralwidget)
        self.LoadCharacter.setObjectName("LoadCharacter")
        self.hboxlayout12.addWidget(self.LoadCharacter)
        self.SaveCharacter = QtGui.QPushButton(self.centralwidget)
        self.SaveCharacter.setObjectName("SaveCharacter")
        self.hboxlayout12.addWidget(self.SaveCharacter)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.hboxlayout12.addWidget(self.line_4)
        self.ExportCharacter = QtGui.QPushButton(self.centralwidget)
        self.ExportCharacter.setObjectName("ExportCharacter")
        self.hboxlayout12.addWidget(self.ExportCharacter)
        self.ExportState = QtGui.QPushButton(self.centralwidget)
        self.ExportState.setEnabled(True)
        self.ExportState.setObjectName("ExportState")
        self.hboxlayout12.addWidget(self.ExportState)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.hboxlayout12.addWidget(self.line_5)
        self.LoadState = QtGui.QPushButton(self.centralwidget)
        self.LoadState.setObjectName("LoadState")
        self.hboxlayout12.addWidget(self.LoadState)
        self.SaveState = QtGui.QPushButton(self.centralwidget)
        self.SaveState.setObjectName("SaveState")
        self.hboxlayout12.addWidget(self.SaveState)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.hboxlayout12.addWidget(self.line_6)
        self.Quit = QtGui.QPushButton(self.centralwidget)
        self.Quit.setObjectName("Quit")
        self.hboxlayout12.addWidget(self.Quit)
        self.vboxlayout.addLayout(self.hboxlayout12)
        self.Status = QtGui.QLabel(self.centralwidget)
        self.Status.setObjectName("Status")
        self.vboxlayout.addWidget(self.Status)
        self.hboxlayout.addLayout(self.vboxlayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tabber.setCurrentIndex(0)
        QtCore.QObject.connect(self.Quit,QtCore.SIGNAL("clicked()"),MainWindow.close)
        QtCore.QObject.connect(self.NewWeaponIsRange,QtCore.SIGNAL("toggled(bool)"),self.NewWeaponRange.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Tabber,self.Name)
        MainWindow.setTabOrder(self.Name,self.Race)
        MainWindow.setTabOrder(self.Race,self.Comment)
        MainWindow.setTabOrder(self.Comment,self.Str)
        MainWindow.setTabOrder(self.Str,self.Dex)
        MainWindow.setTabOrder(self.Dex,self.Con)
        MainWindow.setTabOrder(self.Con,self.Int)
        MainWindow.setTabOrder(self.Int,self.Wil)
        MainWindow.setTabOrder(self.Wil,self.Cha)
        MainWindow.setTabOrder(self.Cha,self.rand_2K6_4)
        MainWindow.setTabOrder(self.rand_2K6_4,self.rand_2K6_6)
        MainWindow.setTabOrder(self.rand_2K6_6,self.rand_KV)
        MainWindow.setTabOrder(self.rand_KV,self.SaveCharacter)
        MainWindow.setTabOrder(self.SaveCharacter,self.ExportCharacter)
        MainWindow.setTabOrder(self.ExportCharacter,self.SaveState)
        MainWindow.setTabOrder(self.SaveState,self.Quit)
        MainWindow.setTabOrder(self.Quit,self.A)
        MainWindow.setTabOrder(self.A,self.M)
        MainWindow.setTabOrder(self.M,self.D)
        MainWindow.setTabOrder(self.D,self.P)
        MainWindow.setTabOrder(self.P,self.R)
        MainWindow.setTabOrder(self.R,self.HP)
        MainWindow.setTabOrder(self.HP,self.MP)
        MainWindow.setTabOrder(self.MP,self.I)
        MainWindow.setTabOrder(self.I,self.HC)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Vorago Player Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Siła fizyczna (Sf)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", " Zręczność (Zr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Żywotność (Żw)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Percepcja (Pr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Siła Woli (Sw)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Charyzma (Ch)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Attack (A, Sf/Zr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Marksmanship (M, Zr/Pr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Defense (D, Zr/Żw)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Power (P, Sw/Pr)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Resistance (R, Sw/Żw)", None, QtGui.QApplication.UnicodeUTF8))
        self.D.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.A.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.M.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.P.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.R.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Punkty Życia (PŻ)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Punkty Mocy (PM)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Inicjatywa (I)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Współczynnik Zdrowienia", None, QtGui.QApplication.UnicodeUTF8))
        self.I.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.HP.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.MP.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.HC.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.rand_2K6_4.setText(QtGui.QApplication.translate("MainWindow", "Losuj 2K6 - 4", None, QtGui.QApplication.UnicodeUTF8))
        self.rand_2K6_4.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+1", None, QtGui.QApplication.UnicodeUTF8))
        self.rand_2K6_6.setText(QtGui.QApplication.translate("MainWindow", "Losuj 2K6 - 6", None, QtGui.QApplication.UnicodeUTF8))
        self.rand_2K6_6.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+2", None, QtGui.QApplication.UnicodeUTF8))
        self.rand_KV.setText(QtGui.QApplication.translate("MainWindow", "Losuj |KV| bez -9, 9, 10", None, QtGui.QApplication.UnicodeUTF8))
        self.rand_KV.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Imię postaci:", None, QtGui.QApplication.UnicodeUTF8))
        self.Name.setText(QtGui.QApplication.translate("MainWindow", "Bez imienia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Rasa:", None, QtGui.QApplication.UnicodeUTF8))
        self.Race.setText(QtGui.QApplication.translate("MainWindow", "Bez rasy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Komentarz:", None, QtGui.QApplication.UnicodeUTF8))
        self.Comment.setText(QtGui.QApplication.translate("MainWindow", "Bez komentarza", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabber.setTabText(self.Tabber.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Współczynniki", None, QtGui.QApplication.UnicodeUTF8))
        self.SkillAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Modyfikator:", None, QtGui.QApplication.UnicodeUTF8))
        self.SkillDel.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabber.setTabText(self.Tabber.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Umiejętności", None, QtGui.QApplication.UnicodeUTF8))
        self.WeaponAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.WeaponDel.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.ArmorAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.ArmorDel.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabber.setTabText(self.Tabber.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Uzbrojenie", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabber.setTabText(self.Tabber.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Eksport postaci", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillDel.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Nazwa:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Modyfikuje:", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "Sf", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "Zr", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "Zw", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "Pr", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "Sw", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "Ch", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillAbility.addItem(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.NewSkillCond.setText(QtGui.QApplication.translate("MainWindow", "Biegłość", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabber.setTabText(self.Tabber.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "Dodaj umiejętności", None, QtGui.QApplication.UnicodeUTF8))
        self.NewWeaponAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.NewWeaponDel.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Nazwa:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "mod. trafienia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "mod. obrażeń", None, QtGui.QApplication.UnicodeUTF8))
        self.NewWeaponIsRange.setText(QtGui.QApplication.translate("MainWindow", "Strzelecka", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Zasięg:", None, QtGui.QApplication.UnicodeUTF8))
        self.NewWeaponSkillAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.NewWeaponSkillDel.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabber.setTabText(self.Tabber.indexOf(self.tab_6), QtGui.QApplication.translate("MainWindow", "Dodaj broń", None, QtGui.QApplication.UnicodeUTF8))
        self.NewArmorAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.NewArmorDel.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Nazwa:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "modyfikator obrony", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "modyfikator wyparowań", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "modyfikator inicjatywy", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabber.setTabText(self.Tabber.indexOf(self.tab_7), QtGui.QApplication.translate("MainWindow", "Dodaj zbroje", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabber.setTabText(self.Tabber.indexOf(self.tab_9), QtGui.QApplication.translate("MainWindow", "Eksport stanu", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Generator postaci Vorago</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\">Autor: <span style=\" font-weight:400;\">Tomasz bla Fortuna</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">E-Mail: </span>bla@thera.be</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Wersja: </span>0.9beta</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Wersja mechaniki:</span> 1.0+</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Licencja: </span>GNU GPLv2</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Opis:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><span style=\" font-weight:400;\">Program służy do generowania pełnych opisów postaci w światach używających mechaniki Vorago. Stworzone opisy służą przede wszystkim do ułatwienia MG przeprowadzania sesji; mogą też służyć do symulowania ataków w kompatybilnym oprogramowaniu.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Pliki programu</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Program potrafi zapisywać do plików stworzone postacie i stan (umiejętności, bronie i zbroje) i potem je odczytywać. Ważne jest by wiedzieć, że pliki postaci zawierają wszystkie dane potrzebne do ich wyświetlenia (w tym fragmenty stanu). Stan będzie modyfikowany podczas ładowania postaci, tj. nieistniejące umiejętności zostaną dodane i różnice zostaną usunięte.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Program automatycznie odczytuje co start swój stan z pliku \"default.vorago\", po dodaniu nowych umiejętnośc/zbroi/broni zalecane jest zapisanie stanu do tego pliku.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.Tabber.setTabText(self.Tabber.indexOf(self.tab_8), QtGui.QApplication.translate("MainWindow", "O programie", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadCharacter.setText(QtGui.QApplication.translate("MainWindow", "Wczytaj postać", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveCharacter.setText(QtGui.QApplication.translate("MainWindow", "Zapisz postać", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveCharacter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.ExportCharacter.setText(QtGui.QApplication.translate("MainWindow", "Eksportuj postać", None, QtGui.QApplication.UnicodeUTF8))
        self.ExportCharacter.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.ExportState.setText(QtGui.QApplication.translate("MainWindow", "Eksportuj stan", None, QtGui.QApplication.UnicodeUTF8))
        self.LoadState.setText(QtGui.QApplication.translate("MainWindow", "Wczytaj stan", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveState.setText(QtGui.QApplication.translate("MainWindow", "Zapisz stan", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveState.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.Quit.setText(QtGui.QApplication.translate("MainWindow", "Wyjście", None, QtGui.QApplication.UnicodeUTF8))
        self.Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.Status.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

